version: '3'

services:
  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ha_picture_frame_test
    volumes:
      - ..:/dev-picture-frame
    ports:
      - "8124:8123"
    restart: unless-stopped
    environment:
      - TZ=America/New_York